In [1]:
import pandas as pd

In [2]:
# reading csv using pandas

In [3]:
data = pd.read_csv('/home/matlab/Downloads/people-100.csv')

In [4]:
# Extracting content of the dataframe

In [5]:
data.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [6]:
# Creating a new row

In [7]:
new_data = {'Index':101,
            'User Id':'A31Her3c201ef58',
            'First Name':'dharshini',
            'Last Name':'R',
            'Sex':'Female',
            'Email':'dharshini@example.com',
            'Phone':9876543210,
            'Date of birth':'2022-06-18',
            'Job Title':'Data Scientist'
           }

In [8]:
# appending the new row to the dataframe

In [9]:
data.loc[3]=new_data

In [10]:
data.head() # to see the changes made

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,101,A31Her3c201ef58,dharshini,R,Female,dharshini@example.com,9876543210,2022-06-18,Data Scientist
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [11]:
# adding chunk of row

In [12]:
new_data2 = {
    'Index': [101, 102],
    'User Id': ['A31Her3c201ef58', 'f90cD3E78f2A9b9'],
    'First Name': ['dharshini', 'agnes'],
    'Last Name': ['R', 'Rachel'],
    'Sex': ['Female', 'Female'],
    'Email': ['dharshini@example.com', 'agnesrachel@example.com'],
    'Phone': [9876543210, '0123456789'],  
    'Date of birth': ['2022-06-18', '2004-09-01'],
    'Job Title': ['Data Scientist', 'Developer']
}

In [13]:
new_df = pd.DataFrame(new_data2)

In [14]:
file_path = 'data.csv' 
new_df.to_csv(file_path, mode='a', header=False, index=False)