# CSI3007 - Advanced Python Programming
# LAB - 14
# NAME: DHARSHINI R
# REG NO: 22MID0132

# EXCEL

In [1]:
# Reading an EXCEL file.
import pandas as pd
data= pd.read_excel("/home/matlab/Downloads/Financial Sample.xlsx")

In [2]:
# extracting data from the excel file
data

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014
698,Government,Canada,Paseo,High,723.0,10,7,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,250,12,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014

In [ ]:
# Query -- given the condition that print all the employee details whos country is Mexico.

In [4]:
res = data[data['Country'] == 'Mexico']

In [5]:
# printing only the empolyee with specific condition

In [6]:
res

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014
10,Midmarket,Mexico,Montana,NaN,2470.0,5,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014
12,Small Business,Mexico,Montana,NaN,958.0,5,300,287400.0,0.0,287400.0,239500.0,47900.0,2014-08-01,8,August,2014
17,Midmarket,Mexico,Paseo,NaN,974.0,10,15,14610.0,0.0,14610.0,9740.0,4870.0,2014-02-01,2,February,2014
21,Government,Mexico,Paseo,NaN,883.0,10,7,6181.0,0.0,6181.0,4415.0,1766.0,2014-08-01,8,August,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,Government,Mexico,Paseo,High,2851.0,10,350,997850.0,149677.5,848172.5,741260.0,106912.5,2014-05-01,5,May,2014
679,Government,Mexico,Paseo,High,2151.0,10,350,752850.0,112927.5,639922.5,559260.0,80662.5,2013-11-01,11,November,2013
682,Channel Partners,Mexico,Velo,High,500.0,120,12,6000.0,900.0,5100.0,1500.0,3600.0,2014-03-01,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.0,139230.0,136500.0,2730.0,2014-10-01,10,October,2014
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.4,8139.6,6840.0,1299.6,2014-02-01,2,February,2014

In [7]:
# writing the query result to a new Excel file

In [8]:
op_file= "Mexico_emp.xlsx"
res.to_excel(op_file, index=False)

In [9]:
op_file

'Mexico_emp.xlsx'

In [10]:
# new file based on the query is created successfully

# JSON

In [11]:
# opening this output file in JSON format

In [12]:
df = pd.read_excel(op_file)

In [13]:
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Midmarket,Mexico,Carretera,NaN,2470,3,15,37050,0.0,37050.0,24700,12350.0,2014-06-01,6,June,2014
1,Midmarket,Mexico,Montana,NaN,2470,5,15,37050,0.0,37050.0,24700,12350.0,2014-06-01,6,June,2014
2,Small Business,Mexico,Montana,NaN,958,5,300,287400,0.0,287400.0,239500,47900.0,2014-08-01,8,August,2014
3,Midmarket,Mexico,Paseo,NaN,974,10,15,14610,0.0,14610.0,9740,4870.0,2014-02-01,2,February,2014
4,Government,Mexico,Paseo,NaN,883,10,7,6181,0.0,6181.0,4415,1766.0,2014-08-01,8,August,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,Government,Mexico,Paseo,High,2851,10,350,997850,149677.5,848172.5,741260,106912.5,2014-05-01,5,May,2014
136,Government,Mexico,Paseo,High,2151,10,350,752850,112927.5,639922.5,559260,80662.5,2013-11-01,11,November,2013
137,Channel Partners,Mexico,Velo,High,500,120,12,6000,900.0,5100.0,1500,3600.0,2014-03-01,3,March,2014
138,Small Business,Mexico,Amarilla,High,546,260,300,163800,24570.0,139230.0,136500,2730.0,2014-10-01,10,October,2014
139,Government,Mexico,Montana,High,1368,5,7,9576,1436.4,8139.6,6840,1299.6,2014-02-01,2,February,2014

In [15]:
json_op = df.to_json(orient="records",indent=4)

In [16]:
op_json = "mex_emp.json"

In [18]:
# save to a JSON file
with open(op_json, "w") as f:
    f.write(json_op)

In [19]:
op_json

'mex_emp.json'

In [20]:
print(op_json)

mex_emp.json

In [21]:
# JSON file is created successfully